---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/boards":
    get:
      summary: Retrieves all boards
      tags:
      - Boards
      security:
      - bearerAuth: []
      responses:
        '200':
          description: boards found
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
        '401':
          description: unauthorized
    post:
      summary: Creates a board
      tags:
      - Boards
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: board created
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
              - title
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
